### ISSUE TITLE
Why is it deprecated?

### ISSUE THREAD

**Issue by flavluc** [realcr/async_mutex#16]
Did you find a better way to solve this kind of problem or you just decided there's no point in implementing `Send` for `MutexGuard`?

I'm having a similar problem:

```
while ... {
    ...
    let sender = sender.lock().unwrap();
    sender.send(event).await.unwrap();
}
```

which outputs the error: `future cannot be sent between threads safely`

**Comment by realcr** [comment]
Hey @flaviolc18, thanks for the interest! I set `async_mutex` to be deprecated because it is unsound in some cases, which I didn't have time to solve. Those cases are mostly related to drops during strange times.

My current suggestion is to use a more maintained piece of code, like this one:
https://docs.rs/async-std/1.5.0/async_std/sync/struct.Mutex.html

**Comment by flavluc** [comment]
Yes, I found about it, there's also [https://tokio-rs.github.io/tokio/doc/tokio/sync/struct.Mutex.html](https://tokio-rs.github.io/tokio/doc/tokio/sync/struct.Mutex.html). But thanks for answering anyway.
